services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    hostname: kafka
    environment:
      # KRaft single-node
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Internal-only listener for other containers
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single-node safe defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app-network

  rest:
    build:
      context: .
      dockerfile: rest/Dockerfile
    container_name: rest
    ports:
      - "8080:8080"
    volumes:
      - ./rest/logs:/app/logs # not a volume, but a bind mount to persist logs
    depends_on:
      - kafka
    networks:
      - app-network

  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    container_name: calculator
    volumes:
      - ./calculator/logs:/app/logs # not a volume, but a bind mount to persist logs
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge